<a href="https://colab.research.google.com/github/madonnagithub/pearly.github.io/blob/master/Day_1__1_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
###### Numpy Basics

In [0]:
#### Shift + Enter - Execute the code and add new Cell

In [0]:
import numpy as np

In [0]:
##### Create an array using numpy (1 D)
a1 = np.array([1,2,3,4,55,6,7,8,10])
a1

array([ 1,  2,  3,  4, 55,  6,  7,  8, 10])

In [0]:
##### Create an array using numpy (2 D)
a2 = np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [0]:
a2.shape  ##(no. of rows,no.of cols)

(3, 4)

In [0]:
a2.ndim

2

In [0]:
a1.ndim

1

In [0]:
a1.shape

(9,)

In [0]:
a2.dtype

dtype('int64')

In [0]:
a2.size

12

In [0]:
##### Create an array using numpy (3 D)
a3 = np.array([[[1,2,3,4],[5,6,7,8],[8,9,10,11]],
               [[1,2,3,4],[5,6,7,8],[8,9,10,11]]])
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11]]])

In [0]:
len(a3)

2

In [0]:
len(a2)

3

In [0]:
a3.shape

(2, 3, 4)

In [0]:
##### Create an array using numpy (3 D)
a4 = np.array([[[1,2,3,4],[5,6,7,8],[8,9,10,11]],
               [[1,2,3,4],[5,6,7,8]]])
a4

array([list([[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]]),
       list([[1, 2, 3, 4], [5, 6, 7, 8]])], dtype=object)

In [0]:
a4.shape

(2,)

In [0]:
### Picking the element from array
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11]]])

In [0]:
a3[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [0]:
a3[0][0]

array([1, 2, 3, 4])

In [0]:
a3[0][0][2]

3

In [0]:
a3[0,0,2]

3

In [0]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [0]:
##### Create an array using numpy (2 D)
a5 = np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11],[12,13,14,15],
               [80,90,100,110],[85,93,12,11]])
a5

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 80,  90, 100, 110],
       [ 85,  93,  12,  11]])

In [0]:
a5[:]

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 80,  90, 100, 110],
       [ 85,  93,  12,  11]])

In [0]:
a5[1:4]   ### print 1st row to 3rd row

array([[ 5,  6,  7,  8],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
a5[1:]

array([[  5,   6,   7,   8],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 80,  90, 100, 110],
       [ 85,  93,  12,  11]])

In [0]:
a5[1:,3] 

array([  8,  11,  15, 110,  11])

In [0]:
a5.shape

(6, 4)

In [0]:
a5.reshape(3,8)    #### (4,6)(12,2)(2,12),(3,8),(8,3)

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 80,  90, 100, 110,  85,  93,  12,  11]])

In [0]:
a5.reshape(2,3,4)

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 80,  90, 100, 110],
        [ 85,  93,  12,  11]]])

In [0]:
a5

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 80,  90, 100, 110],
       [ 85,  93,  12,  11]])

In [0]:
a5.mean()

29.541666666666668

In [0]:
a5.max()

110

In [0]:
a5.min()

1

In [0]:
a5.argmax()

19

In [0]:
a5.argmin()

0

In [0]:
a5.sum()

709

In [0]:
a5

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 80,  90, 100, 110],
       [ 85,  93,  12,  11]])

In [0]:
a5.sum(axis=1)   ### row wise addition

array([ 10,  26,  38,  54, 380, 201])

In [0]:
a5.sum(axis=0)   ### columns wise addition

array([191, 213, 146, 159])

In [0]:
a5

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 80,  90, 100, 110],
       [ 85,  93,  12,  11]])

In [0]:
np.where(a5 == 10)

(array([2]), array([2]))

In [0]:
#### Create a zero matrix
zero = np.zeros((5,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
#### Create a ones matrix
ones = np.ones((5,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
#### Create a identity matrix
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
zero.dtype

dtype('float64')

In [0]:
##### Generate some equidistant numbers between a range
np.linspace(1,100,50)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [0]:
##### Generate some equidistant numbers between a range
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [0]:
np.arange(1,101,3)

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [0]:
#### Random numbers
np.random.randint(10,100)

51

In [0]:
#### Random numbers
np.random.randint(10,100,10)

array([13, 88, 75, 17, 64, 22, 35, 84, 86, 30])

In [0]:
#### Random numbers
np.random.seed(3)
np.random.randint(10,100,10)

array([34, 13, 66, 82, 10, 31, 29, 84, 51, 20])

In [0]:
#### Random numbers
np.random.seed(4)
np.random.randint(10,100,(5,5))

array([[56, 65, 79, 11, 97],
       [82, 60, 19, 68, 65],
       [65, 67, 46, 60, 54],
       [48, 62, 13, 10, 65],
       [31, 31, 83, 48, 66]])

In [0]:
np.random.rand(10)

array([0.04416006, 0.95665297, 0.43614665, 0.94897731, 0.78630599,
       0.8662893 , 0.17316542, 0.07494859, 0.60074272, 0.16797218])

In [0]:
np.random.random((3,3))

array([[0.73338017, 0.40844386, 0.52790882],
       [0.93757158, 0.52169612, 0.10819338],
       [0.15822341, 0.54520265, 0.52440408]])

In [0]:
np.random.randn(4,4)

array([[-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715],
       [-0.60688728,  1.54697933,  0.72334161,  0.04613557]])

In [0]:
np.random.rand(1,100,3)

In [0]:
#### Pandas Basics
#### Series / DataFrame

In [0]:
#### Series
#### It is a kind of array where the index is attached.
#### It converts the data into a sequential form
#### it can hold data like array,list, tuple and dictionary

In [0]:
import pandas as pd

In [0]:
#### Create a series with Pandas
marks = [100,80,90,76,95]
s1 = pd.Series(marks)
s1

0    100
1     80
2     90
3     76
4     95
dtype: int64

In [0]:
#### Create a series with Pandas
marks = (100,80,90,76,95)
s1 = pd.Series(marks)
s1

0    100
1     80
2     90
3     76
4     95
dtype: int64

In [0]:
#### Create a series with Pandas with custom index
marks = (100,80,90,76,95)
subjects = ["Maths","Science","English","Hindi","EVS"]
s2 = pd.Series(marks,index=subjects)
s2

Maths      100
Science     80
English     90
Hindi       76
EVS         95
dtype: int64

In [0]:
### Create series with dictionary
dict = {"Maths":100,"IP":98,"EVS":80,"English":90,"Science":65,"Drawing":90}
s3 = pd.Series(dict)
s3

Maths      100
IP          98
EVS         80
English     90
Science     65
Drawing     90
dtype: int64

In [0]:
s4 = s2 + s3
s4

Drawing      NaN
EVS        175.0
English    180.0
Hindi        NaN
IP           NaN
Maths      200.0
Science    145.0
dtype: float64

In [0]:
s4.head()

Drawing      NaN
EVS        175.0
English    180.0
Hindi        NaN
IP           NaN
dtype: float64

In [0]:
s4.tail()

English    180.0
Hindi        NaN
IP           NaN
Maths      200.0
Science    145.0
dtype: float64

In [0]:
s4.head(3)

Drawing      NaN
EVS        175.0
English    180.0
dtype: float64

In [0]:
s4.head(-4)

Drawing      NaN
EVS        175.0
English    180.0
dtype: float64

In [0]:
s4.head(100)

Drawing      NaN
EVS        175.0
English    180.0
Hindi        NaN
IP           NaN
Maths      200.0
Science    145.0
dtype: float64

In [0]:
s4.iloc[1]

175.0

In [0]:
s4["EVS"]

175.0

In [0]:
s4.loc["EVS"]

175.0

In [0]:
s4

Drawing      NaN
EVS        175.0
English    180.0
Hindi        NaN
IP           NaN
Maths      200.0
Science    145.0
dtype: float64

In [0]:
s4.sort_values()  ## ascending order

Science    145.0
EVS        175.0
English    180.0
Maths      200.0
Drawing      NaN
Hindi        NaN
IP           NaN
dtype: float64

In [0]:
s4.sort_values(ascending=False)  ## descending order

Maths      200.0
English    180.0
EVS        175.0
Science    145.0
Drawing      NaN
Hindi        NaN
IP           NaN
dtype: float64

In [0]:
s4.sort_values(ascending=False,na_position="first")  ## descending order

Drawing      NaN
Hindi        NaN
IP           NaN
Maths      200.0
English    180.0
EVS        175.0
Science    145.0
dtype: float64

In [0]:
s4.sort_index(ascending=False)  ## descending order

Science    145.0
Maths      200.0
IP           NaN
Hindi        NaN
English    180.0
EVS        175.0
Drawing      NaN
dtype: float64

In [0]:
##### DataFrame
#### Simply a collection of series (More than one series)
df = pd.DataFrame(s4)
df

In [0]:
df.reset_index(inplace=True)

In [0]:
df

index      0
0  Drawing    NaN
1      EVS  175.0
2  English  180.0
3    Hindi    NaN
4       IP    NaN
5    Maths  200.0
6  Science  145.0

In [0]:
df.rename(columns={"index":"Subjects",0:"Marks"},inplace=True)
df

Subjects  Marks
0  Drawing    NaN
1      EVS  175.0
2  English  180.0
3    Hindi    NaN
4       IP    NaN
5    Maths  200.0
6  Science  145.0

In [0]:
df["School Name"] = "DPS Delhi"
df

Subjects  Marks School Name
0  Drawing    NaN   DPS Delhi
1      EVS  175.0   DPS Delhi
2  English  180.0   DPS Delhi
3    Hindi    NaN   DPS Delhi
4       IP    NaN   DPS Delhi
5    Maths  200.0   DPS Delhi
6  Science  145.0   DPS Delhi

In [0]:
teacher = ["Mr X","Mr Y","Mr Z","Mr D","Mr C","Mr B","Mr A"]
df["Teacher Name"] = teacher

In [0]:
df

Subjects  Marks School Name Teacher Name
0  Drawing    NaN   DPS Delhi         Mr X
1      EVS  175.0   DPS Delhi         Mr Y
2  English  180.0   DPS Delhi         Mr Z
3    Hindi    NaN   DPS Delhi         Mr D
4       IP    NaN   DPS Delhi         Mr C
5    Maths  200.0   DPS Delhi         Mr B
6  Science  145.0   DPS Delhi         Mr A

In [0]:
df[["Subjects","Marks"]]

In [0]:
df['Marks'].mean()

175.0

In [0]:
df["Marks"] = df["Marks"].fillna(80)
df

Subjects  Marks School Name Teacher Name
0  Drawing   80.0   DPS Delhi         Mr X
1      EVS  175.0   DPS Delhi         Mr Y
2  English  180.0   DPS Delhi         Mr Z
3    Hindi   80.0   DPS Delhi         Mr D
4       IP   80.0   DPS Delhi         Mr C
5    Maths  200.0   DPS Delhi         Mr B
6  Science  145.0   DPS Delhi         Mr A

In [0]:
df.iloc[2]['Marks']

180.0

In [0]:
grade = []
for i in range(0,len(df)):
  marks = df.iloc[i]['Marks']
  if marks > 100:
    grade.append("A")
  else:
    grade.append("B")

In [0]:
df['Grade'] = grade
df

Subjects  Marks School Name Teacher Name Grade
0  Drawing   80.0   DPS Delhi         Mr X     B
1      EVS  175.0   DPS Delhi         Mr Y     A
2  English  180.0   DPS Delhi         Mr Z     A
3    Hindi   80.0   DPS Delhi         Mr D     B
4       IP   80.0   DPS Delhi         Mr C     B
5    Maths  200.0   DPS Delhi         Mr B     A
6  Science  145.0   DPS Delhi         Mr A     A

In [0]:
#### Sort Data
df.sort_values("Marks",ascending=False,inplace=True)
df

Subjects  Marks School Name Teacher Name Grade
5    Maths  200.0   DPS Delhi         Mr B     A
2  English  180.0   DPS Delhi         Mr Z     A
1      EVS  175.0   DPS Delhi         Mr Y     A
6  Science  145.0   DPS Delhi         Mr A     A
0  Drawing   80.0   DPS Delhi         Mr X     B
3    Hindi   80.0   DPS Delhi         Mr D     B
4       IP   80.0   DPS Delhi         Mr C     B

In [0]:
df.reset_index(inplace=True)

In [0]:
df.drop(["index"],axis=1)

index Subjects  Marks School Name Teacher Name Grade
0      5    Maths  200.0   DPS Delhi         Mr B     A
1      2  English  180.0   DPS Delhi         Mr Z     A
2      1      EVS  175.0   DPS Delhi         Mr Y     A
3      6  Science  145.0   DPS Delhi         Mr A     A
4      0  Drawing   80.0   DPS Delhi         Mr X     B
5      3    Hindi   80.0   DPS Delhi         Mr D     B
6      4       IP   80.0   DPS Delhi         Mr C     B